import {
  Globe2,
  Instagram,
  Linkedin,
  PlayCircle,
  Twitter,
  Youtube,
} from "lucide-react";

export const RANGE_OPTIONS = [
  { key: "1M", label: "1 month" },
  { key: "3M", label: "3 month" },
  { key: "6M", label: "6 month" },
  { key: "1Y", label: "1 year" },
];

export const BASE_SERIES = {
  "1M": [
    { label: "W1", value: 82 },
    { label: "W2", value: 91 },
    { label: "W3", value: 98 },
    { label: "W4", value: 113 },
  ],
  "3M": [
    { label: "Jan", value: 112 },
    { label: "Feb", value: 104 },
    { label: "Mar", value: 93 },
    { label: "Apr", value: 88 },
    { label: "May", value: 95 },
    { label: "Jun", value: 108 },
    { label: "Jul", value: 126 },
    { label: "Aug", value: 139 },
    { label: "Sep", value: 133 },
    { label: "Oct", value: 147 },
    { label: "Nov", value: 143 },
    { label: "Dec", value: 156 },
  ],
  "6M": [
    { label: "M1", value: 94 },
    { label: "M2", value: 102 },
    { label: "M3", value: 111 },
    { label: "M4", value: 108 },
    { label: "M5", value: 118 },
    { label: "M6", value: 127 },
    { label: "M7", value: 138 },
    { label: "M8", value: 149 },
    { label: "M9", value: 144 },
    { label: "M10", value: 154 },
    { label: "M11", value: 151 },
    { label: "M12", value: 164 },
  ],
  "1Y": [
    { label: "Jan", value: 61 },
    { label: "Feb", value: 70 },
    { label: "Mar", value: 77 },
    { label: "Apr", value: 86 },
    { label: "May", value: 95 },
    { label: "Jun", value: 103 },
    { label: "Jul", value: 117 },
    { label: "Aug", value: 128 },
    { label: "Sep", value: 141 },
    { label: "Oct", value: 149 },
    { label: "Nov", value: 155 },
    { label: "Dec", value: 169 },
  ],
};

export const PLATFORMS = {
  instagram: {
    key: "instagram",
    label: "Instagram",
    handle: "@neox.studio",
    Icon: Instagram,
    headline: "Audience reach",
    multiplier: 18200,
    drift: 1200,
    momentum: "+8.4%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(159,92,255,0.18),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(59,215,255,0.12),transparent_38%)]",
    stats: {
      audience: "842K",
      engagement: "6.8%",
      clicks: "128K",
      output: "214 posts",
    },
    mix: [
      { label: "Reels", value: 58 },
      { label: "Carousels", value: 27 },
      { label: "Stories", value: 15 },
    ],
    insights: [
      "Reels are carrying most of the save intent in the active window.",
      "Carousel posts are strongest at converting reach into profile visits.",
      "Evening publishing keeps the cleanest engagement lift for premium content.",
    ],
  },
  x: {
    key: "x",
    label: "X",
    handle: "@neoxsignals",
    Icon: Twitter,
    headline: "Post impressions",
    multiplier: 13400,
    drift: 880,
    momentum: "+5.2%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(92,123,255,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(87,189,255,0.10),transparent_38%)]",
    stats: {
      audience: "391K",
      engagement: "4.2%",
      clicks: "84K",
      output: "486 posts",
    },
    mix: [
      { label: "Threads", value: 44 },
      { label: "Short posts", value: 39 },
      { label: "Media posts", value: 17 },
    ],
    insights: [
      "Threads outperform short posts on dwell time and follow-through.",
      "Breaking-topic content still creates the sharpest click spikes.",
      "Lower post density usually improves quality of interaction here.",
    ],
  },
  youtube: {
    key: "youtube",
    label: "YouTube",
    handle: "Neox Media",
    Icon: Youtube,
    headline: "Watch-time reach",
    multiplier: 24400,
    drift: 1520,
    momentum: "+12.1%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(255,93,93,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(255,161,107,0.10),transparent_38%)]",
    stats: {
      audience: "1.24M",
      engagement: "8.1%",
      clicks: "201K",
      output: "78 videos",
    },
    mix: [
      { label: "Long-form", value: 49 },
      { label: "Shorts", value: 38 },
      { label: "Live", value: 13 },
    ],
    insights: [
      "Long-form content gives the most stable retention pattern.",
      "Shorts remain the fastest subscriber acquisition surface.",
      "Thumbnail clarity has a visible effect on session expansion.",
    ],
  },
  linkedin: {
    key: "linkedin",
    label: "LinkedIn",
    handle: "Neox Company",
    Icon: Linkedin,
    headline: "Qualified reach",
    multiplier: 9200,
    drift: 640,
    momentum: "+6.9%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(97,163,255,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(80,225,255,0.10),transparent_38%)]",
    stats: {
      audience: "168K",
      engagement: "5.9%",
      clicks: "39K",
      output: "96 posts",
    },
    mix: [
      { label: "Thought pieces", value: 46 },
      { label: "Case studies", value: 34 },
      { label: "Short updates", value: 20 },
    ],
    insights: [
      "Case-study publishing converts best into qualified inbound attention.",
      "Executive voice posts outperform generic brand-only updates.",
      "Depth matters more than frequency on this surface.",
    ],
  },
  tiktok: {
    key: "tiktok",
    label: "TikTok",
    handle: "@neox.motion",
    Icon: PlayCircle,
    headline: "Viral reach",
    multiplier: 20600,
    drift: 1360,
    momentum: "+14.3%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(68,235,221,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(151,133,255,0.10),transparent_38%)]",
    stats: {
      audience: "913K",
      engagement: "9.2%",
      clicks: "144K",
      output: "302 videos",
    },
    mix: [
      { label: "Trend clips", value: 41 },
      { label: "Explainers", value: 33 },
      { label: "Behind scenes", value: 26 },
    ],
    insights: [
      "Fast-hook openings decide most of the retention result.",
      "Explainers keep stronger save intent than trend-only publishing.",
      "Consistency matters more here than heavy visual polish.",
    ],
  },
  web: {
    key: "web",
    label: "Website",
    handle: "neoxcompany.app",
    Icon: Globe2,
    headline: "Session volume",
    multiplier: 11800,
    drift: 920,
    momentum: "+4.8%",
    heroGlow:
      "bg-[radial-gradient(circle_at_top_left,rgba(110,119,255,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(74,222,128,0.10),transparent_38%)]",
    stats: {
      audience: "—",
      engagement: "3m 42s",
      clicks: "92K",
      output: "41 pages",
    },
    mix: [
      { label: "Social", value: 45 },
      { label: "Direct", value: 37 },
      { label: "Search", value: 18 },
    ],
    insights: [
      "Social-origin sessions convert better on focused campaign pages.",
      "Homepage traffic is broad, but not the strongest for action intent.",
      "Session depth climbs when narrative and CTA stay tightly paired.",
    ],
  },
};