export function buildSetupStudioSceneContract({
  state,
  viewModel,
  actions,
  adapters,
}) {
  return {
    status: {
      loading: state.loading,
      refreshing: state.refreshing,
      importingWebsite: state.importingWebsite,
      savingBusiness: state.savingBusiness,
      actingKnowledgeId: state.actingKnowledgeId,
      savingServiceSuggestion: state.savingServiceSuggestion,
      showRefine: state.showRefine,
      showKnowledge: state.showKnowledge,
      error: state.error,
    },
    forms: {
      businessForm: state.businessForm,
      discoveryForm: state.discoveryForm,
      manualSections: state.manualSections,
    },
    review: {
      discoveryState: state.discoveryState,
      reviewDraft: viewModel.scopedReviewDraft,
      meta: viewModel.effectiveMeta,
      reviewSources: viewModel.visibleSources,
      reviewEvents: viewModel.visibleEvents,
      reviewSyncState: viewModel.reviewSyncState,
      hasStoredReview: viewModel.hasStoredReview,
      hasApprovedTruth: !!state.meta.setupCompleted,
    },
    content: {
      currentTitle: viewModel.currentTitle,
      currentDescription: viewModel.currentDescription,
      discoveryProfileRows: viewModel.discoveryProfileRows,
      knowledgePreview: viewModel.knowledgePreview,
      knowledgeItems: viewModel.visibleKnowledgeItems,
      serviceSuggestionTitle: viewModel.serviceSuggestionTitle,
      studioProgress: viewModel.studioProgress,
      services: state.services,
      hasVisibleResults: viewModel.hasVisibleResults,
      visibleKnowledgeCount: viewModel.visibleKnowledgeItems.length,
      visibleServiceCount: viewModel.visibleServiceItems.length,
    },
    actions: {
      setBusinessField: state.setBusinessField,
      setManualSection: state.setManualSection,
      setDiscoveryField: state.setDiscoveryField,
      scanBusiness: actions.onScanBusiness,
      continueFlow: adapters.continueFlow,
      resumeReview: adapters.loadActiveReview,
      saveBusiness: actions.onSaveBusiness,
      approveKnowledge: actions.onApproveKnowledge,
      rejectKnowledge: actions.onRejectKnowledge,
      createSuggestedService: actions.onCreateSuggestedService,
      openWorkspace: actions.onOpenWorkspace,
      openTruth: adapters.openTruth,
      reloadReviewDraft: adapters.loadActiveReview,
      refresh: adapters.refreshStudio,
      toggleRefine: adapters.toggleRefine,
      toggleKnowledge: adapters.toggleKnowledge,
    },
  };
}
