export const AGENTS = [
  {
    id: "orion",
    name: "Orion",
    role: "Strategist",
    tagline: "Decision architecture, market direction, structured execution.",
    summary:
      "Orion is the high-clarity planning agent for positioning, go-to-market logic, and multi-step execution design.",
    systemPreview:
      "Structured, concise guidance. When asked for a plan, gives numbered steps and closes with a clarifying question.",
    accent: {
      hex: "#67e8f9",
      soft: "rgba(103,232,249,0.18)",
      border: "border-cyan-300/16",
      badge: "border-cyan-300/18 bg-cyan-300/10 text-cyan-100",
      glow: "shadow-[0_0_100px_rgba(34,211,238,0.14)]",
      ring: "from-cyan-300/22 via-sky-400/12 to-transparent",
      text: "text-cyan-100",
      dot: "bg-cyan-300",
    },
    iconVariant: "orion",
    metrics: [
      { label: "Planning depth", value: "High" },
      { label: "Decision style", value: "Structured" },
      { label: "Delivery", value: "Executive" },
    ],
    strengths: ["Strategy maps", "Positioning", "Roadmaps", "Prioritization"],
    usecases: ["Brand strategy", "Launch roadmap", "Growth plan", "Offer design"],
    samplePrompt:
      "Build a 90-day growth strategy for a premium AI agency targeting high-ticket social media clients.",
    capabilities: {
      strategy: 5,
      content: 2,
      funnels: 3,
      analytics: 3,
      messaging: 2,
      planning: 5,
      social: 2,
      kpi: 3,
    },
  },
  {
    id: "nova",
    name: "Nova",
    role: "Content & Instagram",
    tagline: "Hooks, formats, story arcs, editorial momentum.",
    summary:
      "Nova shapes platform-native content systems with stronger hooks, clean formats, and premium social publishing rhythm.",
    systemPreview:
      "Provides content ideas, hooks, formats, and posting plans. Stays concise and ends with one question.",
    accent: {
      hex: "#c084fc",
      soft: "rgba(192,132,252,0.20)",
      border: "border-violet-300/16",
      badge: "border-violet-300/18 bg-violet-300/10 text-violet-100",
      glow: "shadow-[0_0_100px_rgba(168,85,247,0.16)]",
      ring: "from-violet-300/22 via-fuchsia-400/12 to-transparent",
      text: "text-violet-100",
      dot: "bg-violet-300",
    },
    iconVariant: "nova",
    metrics: [
      { label: "Creative flow", value: "High" },
      { label: "Platform fit", value: "Native" },
      { label: "Delivery", value: "Editorial" },
    ],
    strengths: ["Hooks", "Reels ideas", "Carousels", "Posting cadence"],
    usecases: ["Instagram content", "Monthly content plan", "Hook bank", "Reels strategy"],
    samplePrompt:
      "Create 14 Instagram content ideas for a luxury AI command-center brand with premium positioning.",
    capabilities: {
      strategy: 3,
      content: 5,
      funnels: 2,
      analytics: 2,
      messaging: 3,
      planning: 3,
      social: 5,
      kpi: 2,
    },
  },
  {
    id: "atlas",
    name: "Atlas",
    role: "Sales & WhatsApp",
    tagline: "Offer movement, funnel pressure, message conversion.",
    summary:
      "Atlas is built for sales architecture, WhatsApp flows, offer sequencing, and practical conversion design.",
    systemPreview:
      "Provides sales funnel steps, messaging systems, and WhatsApp automation ideas in concise, actionable form.",
    accent: {
      hex: "#fbbf24",
      soft: "rgba(251,191,36,0.18)",
      border: "border-amber-300/16",
      badge: "border-amber-300/18 bg-amber-300/10 text-amber-100",
      glow: "shadow-[0_0_100px_rgba(251,191,36,0.16)]",
      ring: "from-amber-300/22 via-orange-400/12 to-transparent",
      text: "text-amber-100",
      dot: "bg-amber-300",
    },
    iconVariant: "atlas",
    metrics: [
      { label: "Conversion bias", value: "High" },
      { label: "Message tone", value: "Direct" },
      { label: "Delivery", value: "Action-led" },
    ],
    strengths: ["Funnels", "Sales scripts", "WhatsApp flow", "Offer sequencing"],
    usecases: ["WhatsApp funnel", "Sales offer", "Lead nurture", "Closer scripts"],
    samplePrompt:
      "Design a WhatsApp sales funnel for qualified leads coming from Instagram ads into a discovery call.",
    capabilities: {
      strategy: 3,
      content: 2,
      funnels: 5,
      analytics: 2,
      messaging: 5,
      planning: 4,
      social: 2,
      kpi: 2,
    },
  },
  {
    id: "echo",
    name: "Echo",
    role: "Analytics",
    tagline: "Signal clarity, KPI tracking, measurement systems.",
    summary:
      "Echo specializes in tracking plans, reporting logic, KPI architecture, and sharp measurement surfaces.",
    systemPreview:
      "Provides KPI frameworks, tracking plans, measurement logic, and concise analytical guidance with one question.",
    accent: {
      hex: "#34d399",
      soft: "rgba(52,211,153,0.18)",
      border: "border-emerald-300/16",
      badge: "border-emerald-300/18 bg-emerald-300/10 text-emerald-100",
      glow: "shadow-[0_0_100px_rgba(16,185,129,0.14)]",
      ring: "from-emerald-300/22 via-teal-400/12 to-transparent",
      text: "text-emerald-100",
      dot: "bg-emerald-300",
    },
    iconVariant: "echo",
    metrics: [
      { label: "Signal clarity", value: "High" },
      { label: "System style", value: "Precise" },
      { label: "Delivery", value: "Measured" },
    ],
    strengths: ["KPIs", "Tracking plans", "Measurement", "Reporting logic"],
    usecases: ["KPI framework", "Tracking plan", "Performance review", "Dashboard logic"],
    samplePrompt:
      "Create a KPI and tracking framework for an AI services brand running content, DMs, and consultation calls.",
    capabilities: {
      strategy: 3,
      content: 1,
      funnels: 2,
      analytics: 5,
      messaging: 2,
      planning: 4,
      social: 2,
      kpi: 5,
    },
  },
];