export const APP_TOKENS = {
  color: {
    canvas: "#f3f5f8",
    canvasMuted: "#edf1f5",
    surface: "#ffffff",
    surfaceMuted: "#f7f9fc",
    surfaceSubtle: "#f1f4f8",
    surfaceInverse: "#101828",
    text: "#111827",
    textMuted: "#5b6472",
    textSubtle: "#7b8797",
    textInverse: "#f8fafc",
    line: "#d8e0ea",
    lineStrong: "#c7d1de",
    lineSoft: "#e7edf3",
    brand: "#1d4ed8",
    brandEmphasis: "#163fb3",
    brandSoft: "#e8efff",
    success: "#0f766e",
    warning: "#b45309",
    danger: "#be123c",
    info: "#2563eb",
    focus: "rgba(29, 78, 216, 0.18)",
    overlay: "rgba(15, 23, 42, 0.42)",
  },
  shadow: {
    xs: "0 1px 2px rgba(15, 23, 42, 0.04)",
    sm: "0 14px 34px -24px rgba(15, 23, 42, 0.16)",
    md: "0 24px 60px -30px rgba(15, 23, 42, 0.18)",
    lg: "0 36px 96px -40px rgba(15, 23, 42, 0.22)",
  },
  radius: {
    xs: 10,
    sm: 14,
    md: 18,
    lg: 24,
    xl: 30,
    pill: 999,
  },
  font: {
    sans: [
      '"Manrope"',
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      '"Segoe UI"',
      "sans-serif",
    ].join(", "),
    display: [
      '"Plus Jakarta Sans"',
      '"Manrope"',
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      '"Segoe UI"',
      "sans-serif",
    ].join(", "),
  },
  control: {
    height: 42,
    heightLarge: 48,
  },
};

export function getAntdTheme() {
  return {
    cssVar: false,
    hashed: false,
    token: {
      colorPrimary: APP_TOKENS.color.brand,
      colorInfo: APP_TOKENS.color.info,
      colorSuccess: APP_TOKENS.color.success,
      colorWarning: APP_TOKENS.color.warning,
      colorError: APP_TOKENS.color.danger,
      colorText: APP_TOKENS.color.text,
      colorTextSecondary: APP_TOKENS.color.textMuted,
      colorTextTertiary: APP_TOKENS.color.textSubtle,
      colorBgBase: APP_TOKENS.color.canvas,
      colorBgContainer: APP_TOKENS.color.surface,
      colorBgElevated: APP_TOKENS.color.surface,
      colorBgLayout: APP_TOKENS.color.canvas,
      colorFillAlter: APP_TOKENS.color.surfaceMuted,
      colorBorder: APP_TOKENS.color.line,
      colorBorderSecondary: APP_TOKENS.color.lineSoft,
      borderRadius: APP_TOKENS.radius.sm,
      borderRadiusLG: APP_TOKENS.radius.md,
      borderRadiusSM: APP_TOKENS.radius.xs,
      fontFamily: APP_TOKENS.font.sans,
      fontSize: 14,
      controlHeight: APP_TOKENS.control.height,
      controlHeightLG: APP_TOKENS.control.heightLarge,
      boxShadow: APP_TOKENS.shadow.sm,
      boxShadowSecondary: APP_TOKENS.shadow.xs,
      motionDurationFast: "0.16s",
      motionDurationMid: "0.24s",
      motionEaseOutCirc: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    components: {
      Layout: {
        bodyBg: APP_TOKENS.color.canvas,
        siderBg: APP_TOKENS.color.surface,
        headerBg: "rgba(243, 245, 248, 0.84)",
      },
      Button: {
        borderRadius: APP_TOKENS.radius.sm,
        controlHeight: APP_TOKENS.control.height,
        controlHeightLG: APP_TOKENS.control.heightLarge,
        primaryShadow: "none",
        defaultShadow: "none",
        fontWeight: 700,
      },
      Input: {
        borderRadius: APP_TOKENS.radius.sm,
        activeBorderColor: APP_TOKENS.color.brand,
        hoverBorderColor: APP_TOKENS.color.lineStrong,
      },
      Select: {
        borderRadius: APP_TOKENS.radius.sm,
        activeBorderColor: APP_TOKENS.color.brand,
        hoverBorderColor: APP_TOKENS.color.lineStrong,
      },
      Table: {
        borderColor: APP_TOKENS.color.lineSoft,
        headerBg: APP_TOKENS.color.surfaceMuted,
        rowHoverBg: APP_TOKENS.color.surfaceMuted,
      },
      Modal: {
        borderRadiusLG: APP_TOKENS.radius.lg,
        contentBg: APP_TOKENS.color.surface,
        headerBg: APP_TOKENS.color.surface,
      },
      Drawer: {
        borderRadiusLG: APP_TOKENS.radius.lg,
        colorBgElevated: APP_TOKENS.color.surface,
      },
      Tabs: {
        itemColor: APP_TOKENS.color.textMuted,
        itemSelectedColor: APP_TOKENS.color.text,
        itemHoverColor: APP_TOKENS.color.text,
        inkBarColor: APP_TOKENS.color.brand,
      },
      Menu: {
        itemHeight: 42,
        itemMarginBlock: 4,
        itemBorderRadius: APP_TOKENS.radius.sm,
        itemSelectedBg: APP_TOKENS.color.brandSoft,
        itemSelectedColor: APP_TOKENS.color.brandEmphasis,
        itemColor: APP_TOKENS.color.textMuted,
      },
    },
  };
}
