export const APP_TOKENS = {
  color: {
    canvas: "#f5f7fa",
    canvasMuted: "#eef2f6",
    surface: "#ffffff",
    surfaceMuted: "#f8fafc",
    surfaceSubtle: "#f1f5f9",
    surfaceInverse: "#111827",
    text: "#0f172a",
    textMuted: "#475569",
    textSubtle: "#64748b",
    textInverse: "#f8fafc",
    line: "#d7dee7",
    lineStrong: "#c3ced9",
    lineSoft: "#e5ebf2",
    brand: "#2563eb",
    brandEmphasis: "#1d4ed8",
    brandSoft: "#eff6ff",
    info: "#2563eb",
    infoSoft: "#eff6ff",
    success: "#0f766e",
    successSoft: "#f0fdfa",
    warning: "#b45309",
    warningSoft: "#fffbeb",
    danger: "#be123c",
    dangerSoft: "#fff1f2",
    focus: "rgba(37, 99, 235, 0.14)",
    overlay: "rgba(15, 23, 42, 0.22)",
  },
  shadow: {
    xs: "0 1px 2px rgba(15, 23, 42, 0.06)",
    sm: "0 8px 24px rgba(15, 23, 42, 0.08)",
    md: "0 16px 40px rgba(15, 23, 42, 0.10)",
    lg: "0 24px 60px rgba(15, 23, 42, 0.12)",
  },
  radius: {
    xs: 6,
    sm: 6,
    md: 10,
    lg: 14,
    xl: 14,
    pill: 999,
  },
  font: {
    sans: [
      '"Manrope"',
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      '"Segoe UI"',
      "sans-serif",
    ].join(", "),
    display: [
      '"Plus Jakarta Sans"',
      '"Manrope"',
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      '"Segoe UI"',
      "sans-serif",
    ].join(", "),
  },
  control: {
    height: 42,
    heightLarge: 48,
  },
  motion: {
    fast: "0.16s",
    base: "0.22s",
    easeOut: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
};

export function getAntdTheme() {
  return {
    cssVar: false,
    hashed: false,
    token: {
      colorPrimary: APP_TOKENS.color.brand,
      colorInfo: APP_TOKENS.color.info,
      colorSuccess: APP_TOKENS.color.success,
      colorWarning: APP_TOKENS.color.warning,
      colorError: APP_TOKENS.color.danger,
      colorText: APP_TOKENS.color.text,
      colorTextSecondary: APP_TOKENS.color.textMuted,
      colorTextTertiary: APP_TOKENS.color.textSubtle,
      colorBgBase: APP_TOKENS.color.canvas,
      colorBgContainer: APP_TOKENS.color.surface,
      colorBgElevated: APP_TOKENS.color.surface,
      colorBgLayout: APP_TOKENS.color.canvas,
      colorFillAlter: APP_TOKENS.color.surfaceMuted,
      colorBorder: APP_TOKENS.color.line,
      colorBorderSecondary: APP_TOKENS.color.lineSoft,
      borderRadius: APP_TOKENS.radius.sm,
      borderRadiusLG: APP_TOKENS.radius.md,
      borderRadiusSM: APP_TOKENS.radius.xs,
      fontFamily: APP_TOKENS.font.sans,
      fontSize: 14,
      controlHeight: APP_TOKENS.control.height,
      controlHeightLG: APP_TOKENS.control.heightLarge,
      boxShadow: APP_TOKENS.shadow.sm,
      boxShadowSecondary: APP_TOKENS.shadow.xs,
      motionDurationFast: APP_TOKENS.motion.fast,
      motionDurationMid: APP_TOKENS.motion.base,
      motionEaseOutCirc: APP_TOKENS.motion.easeOut,
    },
    components: {
      Layout: {
        bodyBg: APP_TOKENS.color.canvas,
        siderBg: APP_TOKENS.color.surface,
        headerBg: "rgba(245, 247, 250, 0.94)",
      },
      Button: {
        borderRadius: APP_TOKENS.radius.md,
        controlHeight: APP_TOKENS.control.height,
        controlHeightLG: APP_TOKENS.control.heightLarge,
        primaryShadow: "none",
        defaultShadow: "none",
        fontWeight: 700,
      },
      Input: {
        borderRadius: APP_TOKENS.radius.md,
        activeBorderColor: APP_TOKENS.color.brand,
        hoverBorderColor: APP_TOKENS.color.lineStrong,
      },
      Select: {
        borderRadius: APP_TOKENS.radius.md,
        activeBorderColor: APP_TOKENS.color.brand,
        hoverBorderColor: APP_TOKENS.color.lineStrong,
      },
      Table: {
        borderColor: APP_TOKENS.color.lineSoft,
        headerBg: APP_TOKENS.color.surfaceMuted,
        rowHoverBg: APP_TOKENS.color.surfaceMuted,
      },
      Modal: {
        borderRadiusLG: APP_TOKENS.radius.lg,
        contentBg: APP_TOKENS.color.surface,
        headerBg: APP_TOKENS.color.surface,
      },
      Drawer: {
        borderRadiusLG: APP_TOKENS.radius.lg,
        colorBgElevated: APP_TOKENS.color.surface,
      },
      Tabs: {
        itemColor: APP_TOKENS.color.textMuted,
        itemSelectedColor: APP_TOKENS.color.text,
        itemHoverColor: APP_TOKENS.color.text,
        inkBarColor: APP_TOKENS.color.brand,
      },
      Menu: {
        itemHeight: 42,
        itemMarginBlock: 2,
        itemBorderRadius: APP_TOKENS.radius.md,
        itemSelectedBg: APP_TOKENS.color.brandSoft,
        itemSelectedColor: APP_TOKENS.color.brandEmphasis,
        itemColor: APP_TOKENS.color.textMuted,
      },
    },
  };
}
